project:
  type: book
  output-dir: docs

book:
  title: "Scholarship of Teaching and Learning Compendium"
  google-analytics: "G-PL27NX2KY8"
  cover-image: images/heximage.png
  image: images/heximage.png
  favicon: images/favicon.ico
  author: 
  - orcid: 0000-0001-7715-5973
    name:
      family: Paterson
      given: Helena
  - orcid: 0000-0002-4523-2097
    name:
      family: McAleer
      given: Phil
  - orcid: 0000-0002-4191-5245
    name:
      family: Bartlett
      given: James
  date: "04/02/2025"
  sharing:
    - linkedin
  repo-url: https://github.com/BartlettJE/sotl_glossary
  repo-actions: [issue, source]
  chapters:
    - index.qmd
    - Contributors.qmd
    - A.qmd
    - C.qmd
    - D.qmd
    - E.qmd
    - F.qmd
    - G.qmd
    - H.qmd
    - I.qmd
    - K.qmd
    - L.qmd
    - M.qmd
    - N.qmd
    - O.qmd
    - P.qmd
    - Q.qmd
    - R.qmd
    - S.qmd
    - T.qmd
    - V.qmd
    - W.qmd
    - Allterms.qmd
    - references.qmd
  sidebar:
      title: SoTL Compendium
  page-footer:
      left: "CC-BY-SA-4.0 (2025) Helena Paterson, Phil McAleer & James Bartlett"

bibliography: references.bib

format:
  html:
    theme: journal
    number-sections: false
    css: style.css

  
editor: visual

