#  C 
 
## COIL

<dfn>An abbreviation for collaborative online international learning</dfn>

**Long Definition:** 











**Deep Dive:** 



**Contributors:** NA

**Tags:** NA
 
## Co-Creation

<dfn>Development through collaboration</dfn>

**Long Definition:** In an education setting this term most likely refers to staff and students working together to develop novel teaching and assessment approaches











**Deep Dive:** The University of Glasgow Learning and Teaching Conference 2025 was on the theme of Co-Creation and Collaboration and the programme can be viewed here: [https://www.gla.ac.uk/myglasgow/add/events/pastconferencewebpages/annuallearningandteachingconference/](https://www.gla.ac.uk/myglasgow/add/events/pastconferencewebpages/annuallearningandteachingconference/). In addition, a series of presentations on the theme of Co-Creation from the conference can be found on the associated Youtube channel here: [https://www.youtube.com/playlist?list=PLUtE5AlmlvhVBabCbLiGVC-8CyTEHOjRg](https://www.youtube.com/playlist?list=PLUtE5AlmlvhVBabCbLiGVC-8CyTEHOjRg)



**Contributors:** Phil McAleer

**Tags:** NA
 
## Consent

<dfn>Voluntary agreement to take part in an event</dfn>

**Long Definition:** 











**Deep Dive:** 



**Contributors:** NA

**Tags:** NA
 
## Control Groups

<dfn>In experimental design a group that did not experience an intervention</dfn>

**Long Definition:** A group that represented the baseline or default state











**Deep Dive:** 



**Contributors:** NA

**Tags:** NA
