#  P 
 
## P-Value

<dfn>The probability of your data (or more extreme), assuming the null hypothesis is true.</dfn>

Long Definition: 

Under frequentist inferential statistics, the p-value represents the probability of your data (or more extreme), assuming that the null hypothesis is true. Informally, you can see it as a measure of surprise, where a small p-value means your data would be surprising under the null hypothesis. Conversely, a large p-value means your data would not be surprising under the null hypothesis. The idea behind this technique is helping you make decisions where you can either reject the null or retain the null. Given an alpha value (often .05 or 5%), rejecting the null means you conclude there is an effect, whereas retaining the null means you do not conclude there is an effect.











Deep Dive:





Contributors: James Bartlett; Phil McAleer; Helena Paterson

Tags: Statistics
 
## Passive Learning

<dfn>In contrast to active learning, this term is associated with students being exposed to a predominantly an information transmission approach where they have no agency or investment in their learning.</dfn>

Long Definition: 

Students cramming for a test may adopt a superficial approach to learning where the goal or motivation is to regurgitate with the purpose of passing an exam.











Deep Dive:





Contributors: Vicki Dale, Steve Draper

Tags: NA
 
## Pedagogy

<dfn>“The art and science of teaching, pedagogy is the methods of lesson, course, and program delivery.” (Webb & tierney)</dfn>

Long Definition: 













Deep Dive:





Contributors: Katharine Terrell

Tags: NA
 
## Peer Assessment

<dfn>NA</dfn>

Long Definition: 













Deep Dive:





Contributors: NA

Tags: NA
 
## Personalised Learning

<dfn>NA</dfn>

Long Definition: 













Deep Dive:





Contributors: NA

Tags: NA
 
## Problem-Based Learning

<dfn>NA</dfn>

Long Definition: 













Deep Dive:





Contributors: NA

Tags: NA
