#  S 
 
## Sample Size

<dfn>NA</dfn>

**Long Definition:** 











**Deep Dive:** 



**Contributors:** NA

**Tags:** NA
 
## Scholarship

<dfn>NA</dfn>

**Long Definition:** 











**Deep Dive:** 



**Contributors:** NA

**Tags:** NA
 
## SoTL

<dfn>An abbreviation for the phrase scholarship of learning and teaching</dfn>

**Long Definition:** The scholarship of learning and teaching is

“The scholarship of teaching and learning is a rigorous, literature- informed, and peer-reviewed framework for investigating teaching and learning in higher education. It is methodologically flexible and open to many types of inquiries into pedagogical, curricular, disciplinary, and institutional contexts.” (Webb & tierney)









**Deep Dive:** 



**Contributors:** Katharine Terrell

**Tags:** NA
 
## Student Voice

<dfn>NA</dfn>

**Long Definition:** 











**Deep Dive:** 



**Contributors:** NA

**Tags:** NA
 
## Summative Assessment

<dfn>NA</dfn>

**Long Definition:** 











**Deep Dive:** 



**Contributors:** NA

**Tags:** NA
 
## Sustainable

<dfn>NA</dfn>

**Long Definition:** 











**Deep Dive:** 



**Contributors:** NA

**Tags:** NA
 
## Synchronous

<dfn>Happening at the same time; live.</dfn>

**Long Definition:** Synchronous learning activities are those where the teacher and learner are interacting in real time. For example, lectures (online or face-to-face) are typically synchronous - the teacher facilitates learning activities “live” and students engage in the activities in that moment. Compare with “asynchronous”.











**Deep Dive:** 



**Contributors:** Katharine Terrell

**Tags:** NA
